postgres:
  host: "postgres"
  name: "delayed-notifier"
  user: "user"
  port: 5432
http_server:
  address: ":8080"
  timeout: 4
  idle_timeout: 60 
redis:
  host: "redis"
  port: ":6379"
rabbitmq:
  host: "rabbitmq"
  port: ":5672"